require 'rake/testtask'

# Rake::TestTask.new do |t|    # Default name of task is "test"
#   t.pattern = "test/**/*_test.rb"
# end

task :test do
  $LOAD_PATH.unshift('lib', 'test')
  Dir.glob('./test/**/*_test.rb') { |f| require f }
end

task :console do
  require 'irb'
  require 'irb/completion'

  $LOAD_PATH.unshift(File.dirname(__FILE__))
  $LOAD_PATH.unshift(File.dirname(__FILE__) + '/lib')
  $LOAD_PATH.unshift(File.dirname(__FILE__) + '/rental_offer')

  ARGV.clear
  IRB.start
end

task :default => :test
